[package]
name = "rust_commit"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
git = { version = "0.15", package = "git2" }
termion = "2.0.1"
