name: coding365-reminder
run-name: Coding365 Reminder
on:
  schedule:
    - cron: '0 19 * * *'
jobs:
  has-commited:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: |
          if git log --since='12am'>/dev/null 2>&1; then echo 'Commit found, congrats! :)'; exit 0; else echo 'No commit found. :( You better hurry up and get it done.'; exit 130; fi