name: Coding365 Reminder
on:
  schedule:
    - cron: '30 23 * * *'
  workflow_dispatch:
    inputs:
      reason:
        description: 'Reason to run this command'
        required: true
        default: 'Running tests'

jobs:
  has-commited:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: |
          if git log --since='12am'>/dev/null 2>&1; then echo 'Commit found, congrats! :)'; exit 0; else echo 'No commit found. :( You better hurry up and get it done.'; exit 130; fi
  reason:
    if: github.event.inputs.reason
    runs-on: ubuntu-latest
    steps:
      - run: echo "${{github.event.inputs.reason}}"